/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zonafrenel.view;

/**
 *
 * @author Homirrimo
 */
public class InserirDadosView extends javax.swing.JFrame {

    /**
     * Creates new form InserirDadosView
     */
    public InserirDadosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDados = new javax.swing.JPanel();
        labelDistancia = new javax.swing.JLabel();
        labelFrequencia = new javax.swing.JLabel();
        labelAlturaTx = new javax.swing.JLabel();
        labelAlturaRx = new javax.swing.JLabel();
        labelGanhoAntenaTx = new javax.swing.JLabel();
        labelAtenuacaoConector = new javax.swing.JLabel();
        labelAtenuacaoCabo = new javax.swing.JLabel();
        labelGanhoAntenaRx = new javax.swing.JLabel();
        labelPotencia = new javax.swing.JLabel();
        campoDistanciaRaioEnlace = new javax.swing.JTextField();
        campoAlturaTorreRx = new javax.swing.JTextField();
        campoFrequencia = new javax.swing.JTextField();
        campoGanhoAntenaTx = new javax.swing.JTextField();
        campoAtenuacaoCabo = new javax.swing.JTextField();
        campoGanhoAntenaRx = new javax.swing.JTextField();
        campoAlturaTorreTx = new javax.swing.JTextField();
        campoAtenuacaoConector = new javax.swing.JTextField();
        campoPotenciaTransmissor = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        buttonLimparCampos = new javax.swing.JButton();
        buttonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inserir dados");

        labelDistancia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDistancia.setText("Distância Raio Enlace [km]");

        labelFrequencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelFrequencia.setText("Frequência [MHz]");

        labelAlturaTx.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAlturaTx.setText("Altura da Torre Tx [m]");

        labelAlturaRx.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAlturaRx.setText("Altura Torre Rx [m]");

        labelGanhoAntenaTx.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelGanhoAntenaTx.setText("Ganho da Antena Tx [dbi] ");

        labelAtenuacaoConector.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAtenuacaoConector.setText("Atenuação do Conector [dB]");

        labelAtenuacaoCabo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAtenuacaoCabo.setText("Atenuação do Cabo [dB/m]");

        labelGanhoAntenaRx.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelGanhoAntenaRx.setText("Ganho da Antena Rx [dBi]");

        labelPotencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPotencia.setText("Potência Transmissor [W]");

        campoDistanciaRaioEnlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDistanciaRaioEnlaceActionPerformed(evt);
            }
        });

        campoAtenuacaoCabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAtenuacaoCaboActionPerformed(evt);
            }
        });

        campoGanhoAntenaRx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoGanhoAntenaRxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                        .addComponent(labelDistancia)
                        .addGap(18, 18, 18)
                        .addComponent(campoDistanciaRaioEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                        .addComponent(labelAtenuacaoCabo)
                        .addGap(18, 18, 18)
                        .addComponent(campoAtenuacaoCabo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                        .addComponent(labelPotencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(campoPotenciaTransmissor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGanhoAntenaTx)
                    .addComponent(labelFrequencia)
                    .addComponent(labelGanhoAntenaRx))
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDadosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(campoFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoGanhoAntenaTx)
                            .addComponent(campoGanhoAntenaRx))))
                .addGap(30, 30, 30)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                        .addComponent(labelAlturaTx)
                        .addGap(60, 60, 60))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAtenuacaoConector)
                            .addComponent(labelAlturaRx))
                        .addGap(23, 23, 23)))
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoAlturaTorreRx, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(campoAlturaTorreTx)
                    .addComponent(campoAtenuacaoConector)))
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAlturaRx)
                        .addComponent(campoAlturaTorreRx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDistancia)
                        .addComponent(labelFrequencia)
                        .addComponent(campoDistanciaRaioEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPotencia)
                        .addComponent(campoPotenciaTransmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelGanhoAntenaTx)
                        .addComponent(campoGanhoAntenaTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAlturaTx)
                        .addComponent(campoAlturaTorreTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAtenuacaoCabo)
                    .addComponent(campoAtenuacaoCabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGanhoAntenaRx)
                    .addComponent(labelAtenuacaoConector)
                    .addComponent(campoGanhoAntenaRx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAtenuacaoConector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setText("Insira os Dados Para o Cáculo do Raio de Enlace");

        buttonLimparCampos.setText("Limpar Campos");
        buttonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparCamposActionPerformed(evt);
            }
        });

        buttonCalcular.setText("Calcular");
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addComponent(buttonLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(buttonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addComponent(buttonLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesLayout.createSequentialGroup()
                .addComponent(buttonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addGap(35, 35, 35)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1006, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoAtenuacaoCaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAtenuacaoCaboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAtenuacaoCaboActionPerformed

    private void campoDistanciaRaioEnlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDistanciaRaioEnlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDistanciaRaioEnlaceActionPerformed

    private void campoGanhoAntenaRxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoGanhoAntenaRxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGanhoAntenaRxActionPerformed

    private void buttonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimparCamposActionPerformed

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed
        // Desabilita interface de inserirDadosView
        setVisible(false);
        // Vai para InserirDadosView
        new RespostaView().setVisible(true);
    }//GEN-LAST:event_buttonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirDadosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JButton buttonLimparCampos;
    private javax.swing.JTextField campoAlturaTorreRx;
    private javax.swing.JTextField campoAlturaTorreTx;
    private javax.swing.JTextField campoAtenuacaoCabo;
    private javax.swing.JTextField campoAtenuacaoConector;
    private javax.swing.JTextField campoDistanciaRaioEnlace;
    private javax.swing.JTextField campoFrequencia;
    private javax.swing.JTextField campoGanhoAntenaRx;
    private javax.swing.JTextField campoGanhoAntenaTx;
    private javax.swing.JTextField campoPotenciaTransmissor;
    private javax.swing.JLabel labelAlturaRx;
    private javax.swing.JLabel labelAlturaTx;
    private javax.swing.JLabel labelAtenuacaoCabo;
    private javax.swing.JLabel labelAtenuacaoConector;
    private javax.swing.JLabel labelDistancia;
    private javax.swing.JLabel labelFrequencia;
    private javax.swing.JLabel labelGanhoAntenaRx;
    private javax.swing.JLabel labelGanhoAntenaTx;
    private javax.swing.JLabel labelPotencia;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelDados;
    // End of variables declaration//GEN-END:variables
}
